version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/banking_crud
hooks:
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: start_application.sh
      timeout: 300
      runas: root
