version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Zipping the deployment package..."
      - zip -r banking_crud.zip * -x appspec.yml  # Exclude appspec.yml from ZIP
  post_build:
    commands:
      - echo "Build complete. Uploading artifacts..."

artifacts:
  files:
    - banking_crud.zip
    - appspec.yml  # Ensure this is outside the ZIP
  discard-paths: yes
