version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Zipping application..."
      - zip -r banking_crud.zip .   # Ensure this matches artifact paths
artifacts:
  files:
    - banking_crud.zip    # Ensure this matches the name in `build` phase
  discard-paths: yes
